workers_dev = true
name = "my-worker"
main = "./workers/app.ts"
pages_build_output_dir = './build'

# Compatibility
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
binding = "ASSETS"
directory = "./build/client"

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"
PNPM_VERSION = 10
