workers_dev = true
name = "my-worker"
main = "./workers/app.ts"

# Compatibility
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

# assets
assets = { directory = "./build/client/" }

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"
