workers_dev = true
name = "my-worker"
compatibility_date = "2024-11-18"
main = "./workers/app.ts"

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"

[build]
command = "pnpm run cloudflare:build"
