name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Display version info
        run: |
          echo "node `node --version`"
          echo "pnpm `pnpm --version`"
          echo "$CORE_DEPENDENCIES" | xargs pnpm list -r --stream
        env:
          CORE_DEPENDENCIES:
            react
            react-dom
            react-router
            @cloudflare/workers-types
            storybook
            @testing-library/*
            chromatic
            eslint
            typescript
            vite
            vitest
            wrangler
      - name: Check code formatting
        run: pnpm format:check
      - name: Lint
        run: pnpm run -r lint
      - name: Install Playwright
        run: pnpm exec playwright install
        working-directory: apps/website
      - name: Test
        run: pnpm run -r test
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_APPS_WEBSITE }}
          workingDir: apps/website
          autoAcceptChanges: 'main'
          skip: 'dependabot/**'
